#!/bin/bash

# This script reads ./dependencies.tsv and fetches the entries in the
# second column into the first column. A poor man's package manager if
# you will...

function printline {
	echo -en "\e[1A"
	echo -e "\e[0K\r$1"
}

if [ ! -f dependencies.tsv ]; then
	echo "No 'dependencies.tsv' file"
	exit 1
fi

if [ -z $DEST ]; then
	echo "DEST is not defined."
	exit 1
fi

if [ ! -d $DEST ]; then
	echo "Creating $DEST..."
	mkdir -p $DEST
fi

while read -r line
do
	IFS=' ' read target origin <<EOF
`echo $line`
EOF

	if [ -f "$DEST/$target" ]; then
		printline "$target exists. Skip."

	elif [ -z "$origin" ]; then
		echo "Could not parse line: '$line'. Skip."
		exit 1

	else
		install -D /dev/null $DEST/$target

		(curl -L "$origin" --silent --fail -o "$DEST/$target" && printline "Fetched $target" ) || \
			echo "FAILED to fetch $target!"
	fi
done <dependencies.tsv

printline "deps done!"
