name: DEPLOY

on:
  push:
    branches: [ trunk ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install build dependencies
        run: |
          sudo apt-get install -y bmake curl

      - name: Build the thing
        run: |
          bmake build

      - uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: --recursive --verbose --delete-before
          path: dist/
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_key:  ${{ secrets.DEPLOY_KEY }}
