name: PR DEPLOY

on:
  push:
    branches: [ testing-pr-deploy ]

  pull_request:
    branches: [ trunk ]

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
        id: go

      - name: Build the thing
        run: |
          go get -v -d
          go build -v -o mustache mustache.go
          ./bin/build

      - name: Install dependencies
        run: |
          DEST=dist/lib ./bin/deps

      - uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: --recursive --verbose --delete-before --relative
          path: dist/
          remote_path: ${{ secrets.PR_DEPLOY_PATH }}/${{ github.head_ref || github.ref_name }}/website
          remote_host: ${{ secrets.PR_DEPLOY_HOST }}
          remote_port: ${{ secrets.PR_DEPLOY_PORT }}
          remote_user: ${{ secrets.PR_DEPLOY_USER }}
          remote_key:  ${{ secrets.PR_DEPLOY_KEY }}
